api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "picklo-cod-guard"
uid = "25da8fae-1911-4e56-a0c6-588dd8fe7a110123c982"
type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart-payment-methods-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
