# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ec62c461418f2a1ece3f6e5fccc99154"
name = "Picklo"
application_url = "https://rocourier-production.up.railway.app"
embedded = true
handle = "rocourier"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "courier-store-2.myshopify.com"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders-create"

  [[webhooks.subscriptions]]
  topics = [ "orders/cancelled" ]
  uri = "/webhooks/orders-cancelled"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/orders-updated"

  [webhooks.privacy_compliance]
  customer_data_request_url = "/webhooks/customers-data-request"
  customer_deletion_url     = "/webhooks/customers-redact"
  shop_deletion_url         = "/webhooks/shop-redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders,read_shipping,write_fulfillments,write_orders,write_shipping"

[auth]
redirect_urls = [ "https://rocourier-production.up.railway.app/auth/callback" ]

[app_proxy]
url = "https://rocourier-production.up.railway.app/proxy"
subpath = "rocourier"
prefix = "apps"

[pos]
embedded = false
