name = "RoCourier"
client_id = "ec62c461418f2a1ece3f6e5fccc99154"
application_url = "https://rocourier-production.up.railway.app"
embedded = true
handle = "rocourier"

[build]

[access_scopes]
# Full list of required scopes
scopes = "read_orders,write_orders,read_shipping,write_shipping,write_fulfillments,read_fulfillments"

[auth]
redirect_urls = [
  "https://rocourier-production.up.railway.app/auth/callback"
]

[webhooks]
api_version = "2025-01"

[app_proxy]
url = "https://rocourier-production.up.railway.app/proxy"
subpath = "rocourier"
prefix = "apps"

[pos]
embedded = false
