-- Migration: Add Cargus, GLS, Packeta courier integrations
-- AddColumn ShopSettings: cargus, gls, packeta fields

ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "cargusSubscriptionKey" TEXT;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "cargusUsername" TEXT;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "cargusPassword" TEXT;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "cargusEnabled" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "glsUsername" TEXT;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "glsPassword" TEXT;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "glsClientNumber" TEXT;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "glsEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "glsSandbox" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "packetaApiKey" TEXT;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "packetaEnabled" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "cargusHomeDeliveryFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "cargusPickupFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "glsHomeDeliveryFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "glsPickupFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "packetaHomeDeliveryFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "packetaPickupFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
