api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "picklo-delivery-options"
type = "function"
uid = "833eeb8c-4453-01ea-8b56-c43daa5cdf5bc7eada60"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

